name: Gradle Demo
on:
  push:
    branches: [ master ]
jobs:
  gradle-job:
    runs-on: ubuntu-latest
#     container:
#       image: maven:3.8.6-jdk-8    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
       
