name: Gradle Demo
on:
  push:
    branches: [ master ]
jobs:
  gradle-job:
    runs-on: ubuntu-latest
    container:
      image: gradle:7.5.1-jdk8    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
      - name: Build with Gradle
        run: ./gradlew build
       
